### ISSUE TITLE
Nicher - Deprecation warning

### ISSUE THREAD

**Issue by timea-kl** [frontiersi/tenement-tools#3]
Running into deprecation warning and error with the Nicer tool (screenshot attached). It also indicates the CRS is not correct, however I am using the tutorial dataset and the CRS seems to be all correct. 

![image](https://github.com/frontiersi/tenement-tools/assets/46553005/781cf4a9-aac7-4e31-8ddb-b43dd538228f)

**Comment by lachlanhurst** [comment]
Hi @timea-kl . Thanks for reporting this, the 3577 CRS issue was fixed in deae693 and is included in the v1.0.4 release.

We'll keep this issue open for the depreciation warning; it's something I've observed, but haven't yet resolved.

**Comment by Milic-22** [comment]
Thank you Lachlan, I've just tried the latest version of the tool and still getting error with the projection even using the test data that is in 3577. Do you have any suggestion how to resolve the problem?
![image](https://github.com/frontiersi/tenement-tools/assets/105861865/0c1a3eec-bfa3-4035-aac3-3cf0b52d56ea)

**Comment by lachlanhurst** [comment]
Thanks @Milic-22 , it's the same error in a different part of the code that we didn't catch first time around. This has been fixed in 253f517 , but we've not yet packaged a new release.

The easiest way for you to resolve this issue is to replace your version of the `tenement-tools-toolbox.pyt` file with the [latest from this repository](https://github.com/frontiersi/tenement-tools/blob/main/arc/toolbox/tenement-tools-toolbox.pyt). Or even just edit the existing file; it's a single line fix.

There will likely be a new packaged release in the nest week or so.
